name:                aoc2019
version:             0.1.0.0
github:              "ephemient/aoc2019"
license:             BSD3
author:              "Daniel Lin"
maintainer:          "ephemient@gmail.com"
copyright:           "2019 Daniel Lin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ephemient/aoc2019/tree/hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - containers
  - megaparsec
  - mtl
  - primitive
  - split
  - vector

executables:
  aoc2019-exe:
    main:                Main.lhs
    other-modules:
    - Paths_aoc2019
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    - -pgmL markdown-unlit
    dependencies:
    - aoc2019
    - markdown-unlit
  day6-gen:
    main:                Main.hs
    source-dirs:         day6-gen
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    - -pgmL markdown-unlit
    dependencies:
    - containers
    - random

data-files:
- day*.txt

tests:
  aoc2019-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    dependencies:
    - QuickCheck
    - aoc2019
    - array
    - hspec
    - vector

benchmarks:
  aoc2019-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    dependencies:
    - aoc2019
    - criterion
