name: Python CI

on:
  push:
    branches: [ py ]
  pull_request:
    branches: [ py ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile*') }}
          path: |
            ~/.local/share/virtualenv
            ~/.local/share/virtualenvs
      - run: python -m pip install --upgrade pipenv
      - run: |
          pipenv install -d
          pipenv run pytest
